name: "production_deployment"

concurrency: 1

on: 
  push:
    branches:
      - main
    paths:
      - 'first_bundle/**'

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: databricks/setup-cli@main
      
      - name: Deploy to Production
        run: databricks bundle deploy --target prod  # Explicitly specify target
        working-directory: first_bundle
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}  # workspace URL
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          
      # RUN THE JOB
      - name: Run the Job
        run: databricks bundle run first_ci_cd_bundle --target prod
        working-directory: first_bundle
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
